yatube/about/urls.py
from django.urls import path
from .import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name: str = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    # Авторизация
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    # Регистрация
    path('signup/', views.SignUp.as_view(), name='signup'),
    # Выход
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    # Смена пароля
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change',
    ),
    # Сообщение об успешном изменении пароля
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    # Восстановление пароля
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            # success_url = reverse_lazy('users:password_reset_done')
        ),
        name='password_reset',
    ),
    # Сообщение об отправке ссылки для восстановления пароля
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    # Вход по ссылке для восстановления пароля
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    # Сообщение об успешном восстановлении пароля
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/article.html
{% load thumbnail %}
{% with request.resolver_match.view_name as view_name %}
<ul>
    {% if view_name != 'posts:profile' %}
    <li>
    Автор: {{ post.author.get_full_name }}
    <a href={% url 'posts:profile' post.author %}>Все посты пользователя</a>
    {% endif %}
  </li> 
  <li>Дата публикации: {{ post.pub_date|date:'d E Y' }}</li>
</ul>
{% thumbnail post.image "100x100" crop="center" as im %}
  <img class="image" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
{% endthumbnail %}
<p>{{ post.text|linebreaks|truncatewords:90 }}</p>
<a href={% url 'posts:post_detail' post.pk %}>подробная информация</a><br>
{% if view_name != 'posts:group_list' %}
  {% if post.group %} 
    <a href={% url 'posts:group_list' post.group.slug %}>
      {{ post.group.title }}
    </a>
  {% endif %}
{% endif %}
{% endwith %}

yatube/templates/includes/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %} 

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgb(10, 200, 1)">
  <div class="container">
    <a class=static href={% url 'posts:index' %}>
      <img 
        src={% static 'img/logo.png' %} 
        width="30" 
        height="30" 
        class="d-inline-block align-top" 
        alt="logo"
        >
      <span style="color:red">Ya</span>tube</a>
    </a>
    <buttton
      class="navbar-toggler collapsed"
      type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
      >
      <span class="navbar-toggler-icon"></span>
    </buttton>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% with request.resolver_match.view_name as view_name %}
      <ul class="nav  nav-pills">
        <li class="nav-item">              
          <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}" href={% url "about:author" %}>
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}" href={% url "about:tech" %}>
            Технологии
          </a>
        </li>
<!-- пункты меню видны только авторизованному пользователю -->
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}" href= {% url 'posts:post_create' %}>
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:password_change' %}active{% endif %}" href= {% url 'users:password_change' %}>
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href={% url 'users:logout' %}>Выйти</a>
            </li>
            <li class="nav-item">
              Пользователь: {{ user.get_username }}
            <li>
<!-- конец пункты меню видны только авторизованному пользователю -->
<!-- пункты меню видны только неавторизованному пользователю -->
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}" href={% url 'users:login' %}>
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}" href={% url 'users:signup' %}>Регистрация</a>
            </li>
          {% endif %}
          {% endwith %}
<!-- конец пункты меню видны только неавторизованному пользователю -->        
      </ul>
    </div>
  </div>
</nav>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1">Первая</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="page-item active">
        <span class="page-link">{{ i }}</span>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/switcher.html
{% with request.resolver_match.view_name as view_name %}
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if view_name == 'posts:index' %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if view_name == 'posts:follow_index' %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}
{% endwith %}